name: footballscoreapp
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # calendar_strip: ^1.0.7
  table_calendar: ^3.0.5
  top_modal_sheet: ^1.0.0+1
  scroll_to_index: ^2.1.1
  group_button: ^5.0.0
  percent_indicator: ^4.0.0
  flutter_svg: ^1.0.3
  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Black.ttf
  #       - asset: assets/fonts/Roboto-BlackItalic.ttf
  #         style: italic
 